package com.mikedeejay2.mikedeejay2lib.gui.item;

import com.google.common.collect.Multimap;
import com.mikedeejay2.mikedeejay2lib.BukkitPlugin;
import com.mikedeejay2.mikedeejay2lib.gui.GUIContainer;
import com.mikedeejay2.mikedeejay2lib.gui.event.GUIEvent;
import com.mikedeejay2.mikedeejay2lib.gui.event.GUIEventHandler;
import com.mikedeejay2.mikedeejay2lib.item.IItemBuilder;
import com.mikedeejay2.mikedeejay2lib.item.ItemBuilder;
import com.mikedeejay2.mikedeejay2lib.text.Text;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.OfflinePlayer;
import org.bukkit.attribute.Attribute;
import org.bukkit.attribute.AttributeModifier;
import org.bukkit.command.CommandSender;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;
import org.jetbrains.annotations.Nullable;

import java.net.URL;
import java.util.*;

/**
 * Represents an item in a GUI. Holds a few useful things such as:
 * <ul>
 *     <li>An {@link ItemBuilder}</li>
 *     <li>Whether or not it's movable in the GUI or not</li>
 *     <li>GUI Events ({@link GUIEventHandler})</li>
 *     <li>Whether this item has been changed since last being viewed</li>
 *     <li>A map of extra data for keeping a reference to relevant data for this item</li>
 * </ul>
 *
 * @author Mikedeejay2
 */
public class GUIItem implements Cloneable, IItemBuilder<ItemStack, GUIItem> {
    /**
     * The item builder
     */
    protected ItemBuilder item;
    /**
     * Whether this item can be moved
     */
    protected boolean movable;
    /**
     * GUI Events for this item
     */
    protected GUIEventHandler events;
    /**
     * Whether this item has been changed and requires an update
     */
    protected boolean changed;

    /**
     * A nullable map of extra data contained within this item
     */
    protected @Nullable Map<String, Object> extraData;

    /**
     * Construct a new <code>GUIItem</code>
     *
     * @param item The reference base item
     */
    public GUIItem(ItemStack item) {
        this.item = ItemBuilder.of(item);
        this.movable = false;
        this.events = new GUIEventHandler();
        this.setChanged(true);
    }

    /**
     * Construct a new <code>GUIItem</code>
     *
     * @param itemBuilder The reference item builder
     */
    public GUIItem(ItemBuilder itemBuilder) {
        this.item = itemBuilder;
        this.movable = false;
        this.events = new GUIEventHandler();
        this.setChanged(true);
    }

    /**
     * Construct a new <code>GUIItem</code>
     * <p>
     * The item generated by this constructor is stone
     */
    public GUIItem() {
        this(new ItemStack(Material.STONE));
    }

    /**
     * Called when this <code>GUIItem</code> is clicked
     *
     * @param event The event of the click
     * @param gui   The GUI that was clicked on
     */
    public void onClick(InventoryClickEvent event, GUIContainer gui) {
        if(events == null) return;
        events.execute(event, gui);
    }

    /**
     * Returns whether this <code>GUIItem</code> is movable or not
     *
     * @return Move state
     */
    public boolean isMovable() {
        return movable;
    }

    /**
     * Set whether this <code>GUIItem</code> is movable or not
     *
     * @param movable Move state to set this item to
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem setMovable(boolean movable) {
        this.movable = movable;
        return this;
    }

    /**
     * Get the <code>GUIEventHandler</code> of this item
     *
     * @return the item event of this item
     */
    public GUIEventHandler getEvents() {
        return events;
    }

    /**
     * Get a <code>GUIEvent</code> based off of the event's class
     *
     * @param eventClass The class of the <code>GUIEvent</code> to get
     * @param <T>        The class type
     * @return The requested <code>GUIEvent</code>
     */
    public <T extends GUIEvent> T getEvent(Class<T> eventClass) {
        return events.getEvent(eventClass);
    }

    /**
     * Get a <code>GUIEvent</code> based off of the index of the event
     *
     * @param index The index that the <code>GUIEvent</code> is located at in the list
     * @return The requested event
     */
    public GUIEvent getEvent(int index) {
        return events.getEvent(index);
    }

    /**
     * Set the <code>GUIEventHandler</code> for this item
     *
     * @param events Events to set this item to use
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem setEvents(GUIEventHandler events) {
        this.events = events;
        return this;
    }

    /**
     * Add an event to this <code>GUIItem</code>
     *
     * @param event Event to add
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem addEvent(GUIEvent event) {
        events.addEvent(event);
        return this;
    }

    /**
     * Remove an event via instance
     *
     * @param event Event to remove
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem removeEvent(GUIEvent event) {
        events.removeEvent(event);
        return this;
    }

    /**
     * Remove an event via the event's class
     *
     * @param eventClass The class of the event to remove
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem removeEvent(Class<? extends GUIEvent> eventClass) {
        events.removeEvent(eventClass);
        return this;
    }

    /**
     * Returns whether the event instance exists in this <code>GUIEvent</code>
     *
     * @param event The event to search for
     * @return Whether the event exists in this item
     */
    public boolean containsEvent(GUIEvent event) {
        return events.containsEvent(event);
    }

    /**
     * Returns whether an event of a class exists in this <code>GUIEvent</code>
     *
     * @param eventClass The event class to search for
     * @return Whether the event exists in this item
     */
    public boolean containsEvent(Class<? extends GUIEvent> eventClass) {
        return events.containsEvent(eventClass);
    }

    /**
     * Reset the GUI Events for this item
     *
     * @return A reference to this <code>GUIItem</code>
     */
    public GUIItem resetEvents() {
        this.events = new GUIEventHandler();
        return this;
    }

    /**
     * Get whether this item has been changed and requires an update
     *
     * @return Whether this item has been changed and requires an update
     */
    public boolean isChanged() {
        return changed;
    }

    /**
     * Set whether this item has been changed and requires an update
     *
     * @param changed New changed state
     */
    public void setChanged(boolean changed) {
        this.changed = changed;
    }

    /**
     * Whether this item has extra data
     *
     * @return Whether this item has extra data
     */
    public boolean hasExtraData() {
        return extraData != null;
    }

    /**
     * Get this item's extra data map. Could be null.
     *
     * @return Nullable map of extra data
     */
    public @Nullable Map<String, Object> getExtraData() {
        return extraData;
    }

    /**
     * Internal method to initialize extra data when it's needed.
     */
    protected void initExtraData() {
        if(hasExtraData()) return;
        this.extraData = new LinkedHashMap<>();
    }

    /**
     * Add extra data to this item
     *
     * @param key   The key name of the data
     * @param value The data
     * @param <T>   The type of data
     * @return A reference to this object
     */
    public <T> GUIItem addExtraData(String key, T value) {
        initExtraData();
        this.extraData.put(key, value);
        return this;
    }

    /**
     * Get extra data from this item
     *
     * @param key          The key name of the data
     * @param expectedType The expected type of data to get
     * @param <T>          The type of data
     * @return The retrieved extra data
     */
    public <T> T getExtraData(String key, Class<T> expectedType) {
        if(!hasExtraData()) return null;
        return expectedType.cast(this.extraData.get(key));
    }

    /**
     * Get extra data from this item
     *
     * @param key The key name of the data
     * @return The retrieved extra data
     */
    public Object getExtraData(String key) {
        if(!hasExtraData()) return null;
        return this.extraData.get(key);
    }

    /**
     * See if this item contains extra data
     *
     * @param key          The key name of the data
     * @param expectedType The expected type of the data
     * @return Whether the data of the key and expected type are contained within this item
     */
    public boolean containsExtraData(String key, Class<?> expectedType) {
        if(!hasExtraData()) return false;
        if(!this.extraData.containsKey(key)) return false;
        return expectedType.isAssignableFrom(this.extraData.get(key).getClass());
    }

    /**
     * See if this item contains extra data
     *
     * @param key          The key name of the data
     * @return Whether the data is contained within this item
     */
    public boolean containsExtraData(String key) {
        if(!hasExtraData()) return false;
        return this.extraData.containsKey(key);
    }

    /**
     * Remove extra data from this item
     *
     * @param key The key name of the data
     * @return A reference to this object
     */
    public GUIItem removeExtraData(String key) {
        if(!hasExtraData()) return this;
        this.extraData.remove(key);
        return this;
    }

    @Override
    public ItemStack get() {
        return this.item.get();
    }

    @Override
    public ItemStack get(Player player) {
        return this.item.get(player);
    }

    @Override
    public ItemStack get(CommandSender sender) {
        return this.item.get(sender);
    }

    @Override
    public ItemStack get(String locale) {
        return this.item.get(locale);
    }

    @Override
    public GUIItem set(ItemStack item) {
        this.item = this.item.set(item);
        this.setChanged(true);
        return this;
    }

    /**
     * Set the item to a new item
     *
     * @param builder The new item builder
     * @return A reference to this object
     */
    public GUIItem set(ItemBuilder builder) {
        this.item = builder;
        this.setChanged(true);
        return this;
    }

    @Override
    public ItemMeta getMeta() {
        return this.item.getMeta();
    }

    @Override
    public GUIItem setMeta(ItemMeta meta) {
        this.item = this.item.setMeta(meta);
        this.setChanged(true);
        return this;
    }

    @Override
    public String getName() {
        return this.item.getName();
    }

    @Override
    public String getName(Player player) {
        return this.item.getName(player);
    }

    @Override
    public String getName(CommandSender sender) {
        return this.item.getName(sender);
    }

    @Override
    public String getName(String locale) {
        return this.item.getName(locale);
    }

    @Override
    public GUIItem setName(String name) {
        this.item = this.item.setName(name);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setName(Text text) {
        this.item = this.item.setName(text);
        this.setChanged(true);
        return this;
    }

    @Override
    public int getAmount() {
        return this.item.getAmount();
    }

    @Override
    public GUIItem setAmount(int amount) {
        this.item = this.item.setAmount(amount);
        this.setChanged(true);
        return this;
    }

    @Override
    public Material getType() {
        return this.item.getType();
    }

    @Override
    public GUIItem setType(Material material) {
        this.item = this.item.setType(material);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean hasLore() {
        return this.item.hasLore();
    }

    @Override
    public List<String> getLore() {
        return this.item.getLore();
    }

    @Override
    public List<String> getLore(Player player) {
        return this.item.getLore(player);
    }

    @Override
    public List<String> getLore(CommandSender sender) {
        return this.item.getLore(sender);
    }

    @Override
    public List<String> getLore(String locale) {
        return this.item.getLore(locale);
    }

    @Override
    public GUIItem setLore(List<String> lore) {
        this.item = this.item.setLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setLore(String... lore) {
        this.item = this.item.setLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setLoreText(List<Text> lore) {
        this.item = this.item.setLoreText(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setLore(Text... lore) {
        this.item = this.item.setLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(List<String> lore) {
        this.item = this.item.addLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(String... lore) {
        this.item = this.item.addLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(int index, List<String> lore) {
        this.item = this.item.addLore(index, lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(int index, String... lore) {
        this.item = this.item.addLore(index, lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLoreText(List<Text> lore) {
        this.item = this.item.addLoreText(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(Text... lore) {
        this.item = this.item.addLore(lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLoreText(int index, List<Text> lore) {
        this.item = this.item.addLoreText(index, lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addLore(int index, Text... lore) {
        this.item = this.item.addLore(index, lore);
        this.setChanged(true);
        return this;
    }

    @Override
    public Map<Enchantment, Integer> getEnchants() {
        return this.item.getEnchants();
    }

    @Override
    public boolean hasEnchant(Enchantment enchantment) {
        return this.item.hasEnchant(enchantment);
    }

    @Override
    public int getEnchant(Enchantment enchantment) {
        return this.item.getEnchant(enchantment);
    }

    @Override
    public GUIItem removeEnchant(Enchantment enchantment) {
        this.item = this.item.removeEnchant(enchantment);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addEnchant(Enchantment enchantment, int level) {
        this.item = this.item.addEnchant(enchantment, level);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean hasConflictingEnchant(Enchantment enchantment) {
        return this.item.hasConflictingEnchant(enchantment);
    }

    @Override
    public GUIItem addItemFlags(ItemFlag... flags) {
        this.item = this.item.addItemFlags(flags);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeItemFlags(ItemFlag... flags) {
        this.item = this.item.removeItemFlags(flags);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean hasItemFlag(ItemFlag flag) {
        return this.item.hasItemFlag(flag);
    }

    @Override
    public Set<ItemFlag> getItemFlags() {
        return this.item.getItemFlags();
    }

    @Override
    public GUIItem addItemFlag(ItemFlag flag) {
        this.item = this.item.addItemFlag(flag);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addGlow() {
        this.item = this.item.addGlow();
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeGlow() {
        this.item = this.item.removeGlow();
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setEmptyName() {
        this.item = this.item.setEmptyName();
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setUnbreakable(boolean unbreakable) {
        this.item = this.item.setUnbreakable(unbreakable);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean isUnbreakable() {
        return this.item.isUnbreakable();
    }

    @Override
    public OfflinePlayer getHeadOwner() {
        return this.item.getHeadOwner();
    }

    @Override
    public GUIItem setHeadOwner(OfflinePlayer player) {
        this.item = this.item.setHeadOwner(player);
        this.setChanged(true);
        return this;
    }

    @Override
    public String getHeadBase64() {
        return this.item.getHeadBase64();
    }

    @Override
    public URL getHeadUrl() {
        return this.item.getHeadUrl();
    }

    @Override
    public String getHeadUrlAsString() {
        return this.item.getHeadUrlAsString();
    }

    @Override
    public GUIItem setHeadBase64(String base64) {
        this.item = this.item.setHeadBase64(base64);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setHeadUrl(URL url) {
        this.item = this.item.setHeadUrl(url);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setHeadUrl(String url) {
        this.item = this.item.setHeadUrl(url);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean hasAttributeModifiers() {
        return this.item.hasAttributeModifiers();
    }

    @Override
    public Multimap<Attribute, AttributeModifier> getAttributeModifiers() {
        return this.item.getAttributeModifiers();
    }

    @Override
    public Multimap<Attribute, AttributeModifier> getAttributeModifiers(EquipmentSlot slot) {
        return this.item.getAttributeModifiers(slot);
    }

    @Override
    public Collection<AttributeModifier> getAttributeModifiers(Attribute attribute) {
        return this.item.getAttributeModifiers(attribute);
    }

    @Override
    public GUIItem addAttributeModifier(Attribute attribute, AttributeModifier modifier) {
        this.item = this.item.addAttributeModifier(attribute, modifier);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem addAttributeModifiers(Attribute attribute, AttributeModifier... modifiers) {
        this.item = this.item.addAttributeModifiers(attribute, modifiers);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem setAttributeModifiers(Multimap<Attribute, AttributeModifier> attributeModifiers) {
        this.item = this.item.setAttributeModifiers(attributeModifiers);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifier(Attribute attribute) {
        this.item = this.item.removeAttributeModifier(attribute);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifiers(Attribute... attributes) {
        this.item = this.item.removeAttributeModifiers(attributes);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifier(EquipmentSlot slot) {
        this.item = this.item.removeAttributeModifier(slot);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifiers(EquipmentSlot... slots) {
        this.item = this.item.removeAttributeModifiers(slots);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifier(Attribute attribute, AttributeModifier modifier) {
        this.item = this.item.removeAttributeModifier(attribute, modifier);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeAttributeModifiers(Attribute attribute, AttributeModifier... modifiers) {
        this.item = this.item.removeAttributeModifiers(attribute, modifiers);
        this.setChanged(true);
        return this;
    }

    @Override
    public PersistentDataContainer getPersistentDataContainer() {
        return this.item.getPersistentDataContainer();
    }

    @Override
    public GUIItem setCustomModelData(Integer data) {
        this.item = this.item.setCustomModelData(data);
        this.setChanged(true);
        return this;
    }

    @Override
    public int getCustomModelData() {
        return this.item.getCustomModelData();
    }

    @Override
    public boolean hasCustomModelData() {
        return this.item.hasCustomModelData();
    }

    @Override
    public String getDisplayName() {
        return this.item.getDisplayName();
    }

    @Override
    public GUIItem setDisplayName(String name) {
        this.item = this.item.setDisplayName(name);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean hasDisplayName() {
        return this.item.hasDisplayName();
    }

    @Override
    public int getDurability() {
        return this.item.getDurability();
    }

    @Override
    public GUIItem setDurability(int durability) {
        this.item = this.item.setDurability(durability);
        this.setChanged(true);
        return this;
    }

    @Override
    public int getMaxStackSize() {
        return this.item.getMaxStackSize();
    }

    @Override
    public boolean hasDurability() {
        return this.item.hasDurability();
    }

    @Override
    public <Y, Z> GUIItem setData(NamespacedKey key, PersistentDataType<Y, Z> type, Z value) {
        this.item = this.item.setData(key, type, value);
        this.setChanged(true);
        return this;
    }

    @Override
    public <Y, Z> GUIItem setData(BukkitPlugin plugin, String key, PersistentDataType<Y, Z> type, Z value) {
        this.item = this.item.setData(plugin, key, type, value);
        this.setChanged(true);
        return this;
    }

    @Override
    public <Y, Z> boolean hasData(NamespacedKey key, PersistentDataType<Y, Z> type) {
        return this.item.hasData(key, type);
    }

    @Override
    public <Y, Z> boolean hasData(BukkitPlugin plugin, String key, PersistentDataType<Y, Z> type) {
        return this.item.hasData(plugin, key, type);
    }

    @Override
    public <Y, Z> Z getData(NamespacedKey key, PersistentDataType<Y, Z> type) {
        return this.item.getData(key, type);
    }

    @Override
    public <Y, Z> Z getData(BukkitPlugin plugin, String key, PersistentDataType<Y, Z> type) {
        return this.item.getData(plugin, key, type);
    }

    @Override
    public <Y, Z> Z getOrDefaultData(NamespacedKey key, PersistentDataType<Y, Z> type, Z defaultValue) {
        return this.item.getOrDefaultData(key, type, defaultValue);
    }

    @Override
    public <Y, Z> Z getOrDefaultData(BukkitPlugin plugin, String key, PersistentDataType<Y, Z> type, Z defaultValue) {
        return this.item.getOrDefaultData(plugin, key, type, defaultValue);
    }

    @Override
    public GUIItem removeData(NamespacedKey key) {
        this.item = this.item.removeData(key);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeData(BukkitPlugin plugin, String key) {
        this.item = this.item.removeData(plugin, key);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeData(NamespacedKey... keys) {
        this.item = this.item.removeData(keys);
        this.setChanged(true);
        return this;
    }

    @Override
    public GUIItem removeData(BukkitPlugin plugin, String... keys) {
        this.item = this.item.removeData(plugin, keys);
        this.setChanged(true);
        return this;
    }

    @Override
    public boolean isDataEmpty() {
        return this.item.isDataEmpty();
    }

    /**
     * Clone the <code>GUIItem</code>
     *
     * @return The new clones <code>GUIItem</code>
     */
    @Override
    public GUIItem clone() {
        GUIItem newItem;

        try {
            newItem = (GUIItem) super.clone();
        } catch(CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }

        if(item != null) {
            newItem.item = item.clone();
        }

        if(events != null) {
            newItem.events = events.clone();
        }
        return newItem;
    }
}
